using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace CERES.Core.DTO
{
    public class TransactionV2Response
    {
        public int TransactionId { get; set; }
        public string UserName { get; set; }
        public Nullable<System.DateTime> ProductionDate { get; set; }
        public int AccountId { get; set; }
        public int SiteId { get; set; }
        public int LocationId { get; set; }
        public int ServiceAreaId { get; set; }
        public string AccountName { get; set; }
        public string SiteName { get; set; }
        public string LocationName { get; set; }
        public string ServiceAreaName { get; set; }
        public string Remarks { get; set; }
        public Nullable<System.DateTime> CreationDate { get; set; }
        public Nullable<System.DateTime> UpdateDate { get; set; }

        public string StatusCode { get; set; }
        public string UpdateUserID { get; set; }
        public string JOB_ID { get; set; }
    }

    public class TransactionsResponseModel: TransactionV2Response
    {
        public Nullable<decimal> field1 { get; set; }
        public Nullable<decimal> field2 { get; set; }
        public Nullable<decimal> field3 { get; set; }
        public Nullable<decimal> field4 { get; set; }
        public Nullable<decimal> field5 { get; set; }
        public Nullable<decimal> field6 { get; set; }
        public Nullable<decimal> field7 { get; set; }
        public Nullable<decimal> field8 { get; set; }
        public Nullable<decimal> field9 { get; set; }
        public Nullable<decimal> field10 { get; set; }
        public Nullable<decimal> field11 { get; set; }
        public Nullable<decimal> field12 { get; set; }
        public Nullable<decimal> field13 { get; set; }
        public Nullable<decimal> field14 { get; set; }
        public Nullable<decimal> field15 { get; set; }
        public Nullable<decimal> field16 { get; set; }
        public Nullable<decimal> field17 { get; set; }
        public Nullable<decimal> field18 { get; set; }
        public Nullable<decimal> field19 { get; set; }
        public Nullable<decimal> field20 { get; set; }
        public Nullable<decimal> field21 { get; set; }
        public Nullable<decimal> field22 { get; set; }
        public Nullable<decimal> field23 { get; set; }
        public Nullable<decimal> field24 { get; set; }
        public Nullable<decimal> field25 { get; set; }
        public Nullable<decimal> field26 { get; set; }
        public Nullable<decimal> field27 { get; set; }
        public Nullable<decimal> field28 { get; set; }
        public Nullable<decimal> field29 { get; set; }
        public Nullable<decimal> field30 { get; set; }
        public Nullable<decimal> field31 { get; set; }
        public Nullable<decimal> field32 { get; set; }
        public Nullable<decimal> field33 { get; set; }
        public Nullable<decimal> field34 { get; set; }
        public Nullable<decimal> field35 { get; set; }
        public Nullable<decimal> field36 { get; set; }
        public Nullable<decimal> field37 { get; set; }
        public Nullable<decimal> field38 { get; set; }
        public Nullable<decimal> field39 { get; set; }
        public Nullable<decimal> field40 { get; set; }
        public Nullable<decimal> field41 { get; set; }
        public Nullable<decimal> field42 { get; set; }
        public Nullable<decimal> field43 { get; set; }
        public Nullable<decimal> field44 { get; set; }
        public Nullable<decimal> field45 { get; set; }
        public Nullable<decimal> field46 { get; set; }
        public Nullable<decimal> field47 { get; set; }
        public Nullable<decimal> field48 { get; set; }
        public Nullable<decimal> field49 { get; set; }
        public Nullable<decimal> field50 { get; set; }
        public Nullable<decimal> field51 { get; set; }
        public Nullable<decimal> field52 { get; set; }
        public Nullable<decimal> field53 { get; set; }
        public Nullable<decimal> field54 { get; set; }
        public Nullable<decimal> field55 { get; set; }
        public Nullable<decimal> field56 { get; set; }
        public Nullable<decimal> field57 { get; set; }
        public Nullable<decimal> field58 { get; set; }
        public Nullable<decimal> field59 { get; set; }
        public Nullable<decimal> field60 { get; set; }
        public Nullable<decimal> field61 { get; set; }
        public Nullable<decimal> field62 { get; set; }
        public Nullable<decimal> field63 { get; set; }
        public Nullable<decimal> field64 { get; set; }
        public Nullable<decimal> field65 { get; set; }
        public Nullable<decimal> field66 { get; set; }
        public Nullable<decimal> field67 { get; set; }
        public Nullable<decimal> field68 { get; set; }
        public Nullable<decimal> field69 { get; set; }
        public Nullable<decimal> field70 { get; set; }
        public Nullable<decimal> field71 { get; set; }
        public Nullable<decimal> field72 { get; set; }
        public Nullable<decimal> field73 { get; set; }
        public Nullable<decimal> field74 { get; set; }
        public Nullable<decimal> field75 { get; set; }
        public Nullable<decimal> field76 { get; set; }
        public Nullable<decimal> field77 { get; set; }
        public Nullable<decimal> field78 { get; set; }
        public Nullable<decimal> field79 { get; set; }
        public Nullable<decimal> field80 { get; set; }
        public Nullable<decimal> field81 { get; set; }
        public Nullable<decimal> field82 { get; set; }
        public Nullable<decimal> field83 { get; set; }
        public Nullable<decimal> field84 { get; set; }
        public Nullable<decimal> field85 { get; set; }
        public Nullable<decimal> field86 { get; set; }
        public Nullable<decimal> field87 { get; set; }
        public Nullable<decimal> field88 { get; set; }
        public Nullable<decimal> field89 { get; set; }
        public Nullable<decimal> field90 { get; set; }

        public Nullable<decimal> field91 { get; set; }
        public Nullable<decimal> field92 { get; set; }
        public Nullable<decimal> field93 { get; set; }
        public Nullable<decimal> field94 { get; set; }
        public Nullable<decimal> field95 { get; set; }
        public Nullable<decimal> field96 { get; set; }
        public Nullable<decimal> field97 { get; set; }
        public Nullable<decimal> field98 { get; set; }
        public Nullable<decimal> field99 { get; set; }
        public Nullable<decimal> field100 { get; set; }

        public Nullable<decimal> field101 { get; set; }
        public Nullable<decimal> field102 { get; set; }
        public Nullable<decimal> field103 { get; set; }
        public Nullable<decimal> field104 { get; set; }
        public Nullable<decimal> field105 { get; set; }
        public Nullable<decimal> field106 { get; set; }
        public Nullable<decimal> field107 { get; set; }
        public Nullable<decimal> field108 { get; set; }
        public Nullable<decimal> field109 { get; set; }
        public Nullable<decimal> field110 { get; set; }

        public Nullable<decimal> field111 { get; set; }
        public Nullable<decimal> field112 { get; set; }
        public Nullable<decimal> field113 { get; set; }
        public Nullable<decimal> field114 { get; set; }
        public Nullable<decimal> field115 { get; set; }
        public Nullable<decimal> field116 { get; set; }
        public Nullable<decimal> field117 { get; set; }
        public Nullable<decimal> field118 { get; set; }
        public Nullable<decimal> field119 { get; set; }
        public Nullable<decimal> field120 { get; set; }

        public Nullable<decimal> field121 { get; set; }
        public Nullable<decimal> field122 { get; set; }
        public Nullable<decimal> field123 { get; set; }
        public Nullable<decimal> field124 { get; set; }
        public Nullable<decimal> field125 { get; set; }
        public Nullable<decimal> field126 { get; set; }
        public Nullable<decimal> field127 { get; set; }
        public Nullable<decimal> field128 { get; set; }
        public Nullable<decimal> field129 { get; set; }
        public Nullable<decimal> field130 { get; set; }

        public Nullable<decimal> field131 { get; set; }
        public Nullable<decimal> field132 { get; set; }
        public Nullable<decimal> field133 { get; set; }
        public Nullable<decimal> field134 { get; set; }
        public Nullable<decimal> field135 { get; set; }
        public Nullable<decimal> field136 { get; set; }
        public Nullable<decimal> field137 { get; set; }
        public Nullable<decimal> field138 { get; set; }
        public Nullable<decimal> field139 { get; set; }
        public Nullable<decimal> field140 { get; set; }

        public Nullable<decimal> field141 { get; set; }
        public Nullable<decimal> field142 { get; set; }
        public Nullable<decimal> field143 { get; set; }
        public Nullable<decimal> field144 { get; set; }
        public Nullable<decimal> field145 { get; set; }
        public Nullable<decimal> field146 { get; set; }
        public Nullable<decimal> field147 { get; set; }
        public Nullable<decimal> field148 { get; set; }
        public Nullable<decimal> field149 { get; set; }
        public Nullable<decimal> field150 { get; set; }

        public Nullable<decimal> field151 { get; set; }
        public Nullable<decimal> field152 { get; set; }
        public Nullable<decimal> field153 { get; set; }
        public Nullable<decimal> field154 { get; set; }
        public Nullable<decimal> field155 { get; set; }
        public Nullable<decimal> field156 { get; set; }
        public Nullable<decimal> field157 { get; set; }
        public Nullable<decimal> field158 { get; set; }
        public Nullable<decimal> field159 { get; set; }
        public Nullable<decimal> field160 { get; set; }

        public Nullable<decimal> field161 { get; set; }
        public Nullable<decimal> field162 { get; set; }
        public Nullable<decimal> field163 { get; set; }
        public Nullable<decimal> field164 { get; set; }
        public Nullable<decimal> field165 { get; set; }
        public Nullable<decimal> field166 { get; set; }
        public Nullable<decimal> field167 { get; set; }
        public Nullable<decimal> field168 { get; set; }
        public Nullable<decimal> field169 { get; set; }
        public Nullable<decimal> field170 { get; set; }

        public Nullable<decimal> field171 { get; set; }
        public Nullable<decimal> field172 { get; set; }
        public Nullable<decimal> field173 { get; set; }
        public Nullable<decimal> field174 { get; set; }
        public Nullable<decimal> field175 { get; set; }
        public Nullable<decimal> field176 { get; set; }
        public Nullable<decimal> field177 { get; set; }
        public Nullable<decimal> field178 { get; set; }
        public Nullable<decimal> field179 { get; set; }
        public Nullable<decimal> field180 { get; set; }

        public Nullable<decimal> field181 { get; set; }
        public Nullable<decimal> field182 { get; set; }
        public Nullable<decimal> field183 { get; set; }
        public Nullable<decimal> field184 { get; set; }
        public Nullable<decimal> field185 { get; set; }
        public Nullable<decimal> field186 { get; set; }
        public Nullable<decimal> field187 { get; set; }
        public Nullable<decimal> field188 { get; set; }
        public Nullable<decimal> field189 { get; set; }
        public Nullable<decimal> field190 { get; set; }

        public Nullable<decimal> field191 { get; set; }
        public Nullable<decimal> field192 { get; set; }
        public Nullable<decimal> field193 { get; set; }
        public Nullable<decimal> field194 { get; set; }
        public Nullable<decimal> field195 { get; set; }
        public Nullable<decimal> field196 { get; set; }
        public Nullable<decimal> field197 { get; set; }
        public Nullable<decimal> field198 { get; set; }
        public Nullable<decimal> field199 { get; set; }
        public Nullable<decimal> field200 { get; set; }

        public string StringField1 { get; set; }
        public string StringField2 { get; set; }
        public string StringField3 { get; set; }
        public string StringField4 { get; set; }
        public string StringField5 { get; set; }
        public string StringField6 { get; set; }
        public string StringField7 { get; set; }
        public string StringField8 { get; set; }
        public string StringField9 { get; set; }
        public string StringField10 { get; set; }
        public string StringField11 { get; set; }
        public string StringField12 { get; set; }
        public string StringField13 { get; set; }
        public string StringField14 { get; set; }
        public string StringField15 { get; set; }
        public string StringField16 { get; set; }
        public string StringField17 { get; set; }
        public string StringField18 { get; set; }
        public string StringField19 { get; set; }
        public string StringField20 { get; set; }
        public string StringField21 { get; set; }
        public string StringField22 { get; set; }
        public string StringField23 { get; set; }
        public string StringField24 { get; set; }
        public string StringField25 { get; set; }
        public string StringField26 { get; set; }
        public string StringField27 { get; set; }
        public string StringField28 { get; set; }
        public string StringField29 { get; set; }
        public string StringField30 { get; set; }
        public string StringField31 { get; set; }
        public string StringField32 { get; set; }
        public string StringField33 { get; set; }
        public string StringField34 { get; set; }
        public string StringField35 { get; set; }
        public string StringField36 { get; set; }
        public string StringField37 { get; set; }
        public string StringField38 { get; set; }
        public string StringField39 { get; set; }
        public string StringField40 { get; set; }
        public string StringField41 { get; set; }
        public string StringField42 { get; set; }
        public string StringField43 { get; set; }
        public string StringField44 { get; set; }
        public string StringField45 { get; set; }
        public string StringField46 { get; set; }
        public string StringField47 { get; set; }
        public string StringField48 { get; set; }
        public string StringField49 { get; set; }
        public string StringField50 { get; set; }
        public string StringField51 { get; set; }
        public string StringField52 { get; set; }
        public string StringField53 { get; set; }
        public string StringField54 { get; set; }
        public string StringField55 { get; set; }
        public string StringField56 { get; set; }
        public string StringField57 { get; set; }
        public string StringField58 { get; set; }
        public string StringField59 { get; set; }
        public string StringField60 { get; set; }
        public string StringField61 { get; set; }
        public string StringField62 { get; set; }
        public string StringField63 { get; set; }
        public string StringField64 { get; set; }
        public string StringField65 { get; set; }
        public string StringField66 { get; set; }
        public string StringField67 { get; set; }
        public string StringField68 { get; set; }
        public string StringField69 { get; set; }
        public string StringField70 { get; set; }
        public string StringField71 { get; set; }
        public string StringField72 { get; set; }
        public string StringField73 { get; set; }
        public string StringField74 { get; set; }
        public string StringField75 { get; set; }
        public string StringField76 { get; set; }
        public string StringField77 { get; set; }
        public string StringField78 { get; set; }
        public string StringField79 { get; set; }
        public string StringField80 { get; set; }
        public string StringField81 { get; set; }
        public string StringField82 { get; set; }
        public string StringField83 { get; set; }
        public string StringField84 { get; set; }
        public string StringField85 { get; set; }
        public string StringField86 { get; set; }
        public string StringField87 { get; set; }
        public string StringField88 { get; set; }
        public string StringField89 { get; set; }
        public string StringField90 { get; set; }

        public string StringField91 { get; set; }
        public string StringField92 { get; set; }
        public string StringField93 { get; set; }
        public string StringField94 { get; set; }
        public string StringField95 { get; set; }
        public string StringField96 { get; set; }
        public string StringField97 { get; set; }
        public string StringField98 { get; set; }
        public string StringField99 { get; set; }
        public string StringField100 { get; set; }

        public string StringField101 { get; set; }
        public string StringField102 { get; set; }
        public string StringField103 { get; set; }
        public string StringField104 { get; set; }
        public string StringField105 { get; set; }
        public string StringField106 { get; set; }
        public string StringField107 { get; set; }
        public string StringField108 { get; set; }
        public string StringField109 { get; set; }
        public string StringField110 { get; set; }

        public string StringField111 { get; set; }
        public string StringField112 { get; set; }
        public string StringField113 { get; set; }
        public string StringField114 { get; set; }
        public string StringField115 { get; set; }
        public string StringField116 { get; set; }
        public string StringField117 { get; set; }
        public string StringField118 { get; set; }
        public string StringField119 { get; set; }
        public string StringField120 { get; set; }

        public string StringField121 { get; set; }
        public string StringField122 { get; set; }
        public string StringField123 { get; set; }
        public string StringField124 { get; set; }
        public string StringField125 { get; set; }
        public string StringField126 { get; set; }
        public string StringField127 { get; set; }
        public string StringField128 { get; set; }
        public string StringField129 { get; set; }
        public string StringField130 { get; set; }

        public string StringField131 { get; set; }
        public string StringField132 { get; set; }
        public string StringField133 { get; set; }
        public string StringField134 { get; set; }
        public string StringField135 { get; set; }
        public string StringField136 { get; set; }
        public string StringField137 { get; set; }
        public string StringField138 { get; set; }
        public string StringField139 { get; set; }
        public string StringField140 { get; set; }

        public string StringField141 { get; set; }
        public string StringField142 { get; set; }
        public string StringField143 { get; set; }
        public string StringField144 { get; set; }
        public string StringField145 { get; set; }
        public string StringField146 { get; set; }
        public string StringField147 { get; set; }
        public string StringField148 { get; set; }
        public string StringField149 { get; set; }
        public string StringField150 { get; set; }

        public string StringField151 { get; set; }
        public string StringField152 { get; set; }
        public string StringField153 { get; set; }
        public string StringField154 { get; set; }
        public string StringField155 { get; set; }
        public string StringField156 { get; set; }
        public string StringField157 { get; set; }
        public string StringField158 { get; set; }
        public string StringField159 { get; set; }
        public string StringField160 { get; set; }

        public string StringField161 { get; set; }
        public string StringField162 { get; set; }
        public string StringField163 { get; set; }
        public string StringField164 { get; set; }
        public string StringField165 { get; set; }
        public string StringField166 { get; set; }
        public string StringField167 { get; set; }
        public string StringField168 { get; set; }
        public string StringField169 { get; set; }
        public string StringField170 { get; set; }

        public string StringField171 { get; set; }
        public string StringField172 { get; set; }
        public string StringField173 { get; set; }
        public string StringField174 { get; set; }
        public string StringField175 { get; set; }
        public string StringField176 { get; set; }
        public string StringField177 { get; set; }
        public string StringField178 { get; set; }
        public string StringField179 { get; set; }
        public string StringField180 { get; set; }

        public string StringField181 { get; set; }
        public string StringField182 { get; set; }
        public string StringField183 { get; set; }
        public string StringField184 { get; set; }
        public string StringField185 { get; set; }
        public string StringField186 { get; set; }
        public string StringField187 { get; set; }
        public string StringField188 { get; set; }
        public string StringField189 { get; set; }
        public string StringField190 { get; set; }

        public string StringField191 { get; set; }
        public string StringField192 { get; set; }
        public string StringField193 { get; set; }
        public string StringField194 { get; set; }
        public string StringField195 { get; set; }
        public string StringField196 { get; set; }
        public string StringField197 { get; set; }
        public string StringField198 { get; set; }
        public string StringField199 { get; set; }
        public string StringField200 { get; set; }

    }
}