//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CERES.Core.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class location
    {
        public int locID { get; set; }
        public int siteID { get; set; }
        public string locName { get; set; }
        public bool locStatus { get; set; }
        public string Continent { get; set; }
        public string Country { get; set; }
        public string CBPSRegion { get; set; }
        public string State { get; set; }
        public string City { get; set; }
        public string Campus { get; set; }
        public string Building { get; set; }
        public string Floor { get; set; }
        public string Area { get; set; }
        public string Office { get; set; }
        public System.DateTime createDate { get; set; }
        public int UIEnabledInd { get; set; }
    }
}
