//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CERES.Core.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class ServiceAreaField
    {
        public int svcFieldID { get; set; }
        public int svcID { get; set; }
        public int svcFieldNumber { get; set; }
        public string svcFieldName { get; set; }
        public string CategoryCode { get; set; }
        public Nullable<bool> IsVisible { get; set; }
        public string Shade { get; set; }
        public string Description_Txt { get; set; }
        public Nullable<int> ServiceAreaFieldGroup_SAID { get; set; }
        public Nullable<short> FieldType { get; set; }
        public string DataType { get; set; }
        public string GroupName { get; set; }
        public string MetricShortName { get; set; }
        public string MetricFormat { get; set; }
        public string DefaultValue { get; set; }
        public Nullable<int> IsLogVisible { get; set; }
        public Nullable<short> IsMandatory { get; set; }
        public string Constraint_Txt { get; set; }
    }
}
