//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CERES.Core.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class ServiceArea
    {
        public int svcID { get; set; }
        public int locID { get; set; }
        public string svcName { get; set; }
        public bool svcStatus { get; set; }
        public System.DateTime createDate { get; set; }
        public string ServiceCategory { get; set; }
    }
}
