//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CERES.Core.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class site
    {
        public int siteID { get; set; }
        public int clientID { get; set; }
        public string siteName { get; set; }
        public bool siteStatus { get; set; }
        public System.DateTime createDate { get; set; }
        public string siteFolderName { get; set; }
    }
}
