//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CERES.Core.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class user
    {
        public int UserID { get; set; }
        public string fullname { get; set; }
        public string userName { get; set; }
        public byte[] userPwd { get; set; }
        public Nullable<byte> userStatus { get; set; }
        public string AccountType { get; set; }
        public string UserClientSiteFolderName { get; set; }
        public Nullable<int> ClientID { get; set; }
        public string ClientFolderName { get; set; }
        public Nullable<bool> resetflag { get; set; }
        public Nullable<System.DateTime> lastlogin_dttm { get; set; }
        public Nullable<int> visit_cnt { get; set; }
        public Nullable<short> admin { get; set; }
        public string managerUserName { get; set; }
        public string managerFullName { get; set; }
        public System.DateTime Creation_Dttm { get; set; }
        public string Creation_UserID { get; set; }
        public Nullable<System.DateTime> Modification_Dttm { get; set; }
        public string Modification_UserID { get; set; }
        public string company_nm { get; set; }
        public string contact_phone_nbr { get; set; }
        public Nullable<byte> Upload_ind { get; set; }
        public Nullable<byte> GoldReports_ind { get; set; }
        public Nullable<byte> MstrUser_Ind { get; set; }
    }
}
