//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CERES.Core.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class vwGet_ClientList2
    {
        public int ID { get; set; }
        public string name { get; set; }
        public int userid { get; set; }
        public string username { get; set; }
    }
}
