//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CERES.Core.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class vwServiceAreaFieldLOV
    {
        public int ServiceAreaFieldLOV_SAID { get; set; }
        public int svcFieldId { get; set; }
        public Nullable<int> FieldId { get; set; }
        public string FieldText { get; set; }
        public string FieldName { get; set; }
    }
}
